services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=devopsvika
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=dbku
    ports:
      - "5002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devopsvika -d dbku"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://devopsvika:secret123@db:5432/dbku
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend