services:
  - type: web
    name: testing-devops-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: testing-devops-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001
